{{ $count := default 3 .Values.options.enableMultiKafka | add 1 | int  }}
{{- range untilStep 1 $count 1 }}
---
apiVersion: v1
kind: Service
metadata:
    name: kafka00{{ . }}
    namespace: {{ $.Release.Namespace }}
    labels:
        name: kafka00{{ . }}
spec:
    selector:
        name: kafka00{{ . }}
    ports:
    -   name: kafka
        port: 9092
        targetPort: 9092
{{- end }}
