{{ $count := default 3 .Values.options.enableMultiMongo | add 1 | int  }}
{{- range untilStep 1 $count 1 }}
---
apiVersion: v1
kind: Service
metadata:
    name: mongo00{{ . }}
    namespace: {{ $.Release.Namespace }}
    labels:
        name: mongo00{{ . }}
spec:
    selector:
        name: mongo00{{ . }}
    ports:
    -   name: mongos
        port: 30000
        targetPort: 30000
    -   name: config
        port: 20000
        targetPort: 20000
    -   name: shart1
        port: 27017
        targetPort: 27017
    -   name: shart2
        port: 27018
        targetPort: 27018
    -   name: shart3
        port: 27019
        targetPort: 27019
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
    name: mongo-client
    namespace: {{ .Release.Namespace  }}
    labels:
      name: mongo001
spec:
    selector:
        name: mongo001
    type: NodePort
    ports:
    -   name: mongo-client
        port: 30000
